import { FetchedRequestObj } from "../types/Request";

export const mockRequests: FetchedRequestObj[] = [
  {
    requestId: "REQ-1001",
    blockchainId: "BC-9001",
    item: "A4 Books",
    quantity: 50,
    priority: "High",
    reason: "For student examinations",
    status: "approved",
    from: { userId: "U-101", departmentId: "D-001", departmentName: "Finance" },
  },
  {
    requestId: "REQ-1002",
    blockchainId: "BC-9002",
    item: "Pens",
    quantity: 120,
    priority: "Low",
    reason: "Daily office use",
    status: "pending",
    from: { userId: "U-102", departmentId: "D-002", departmentName: "HR" },
  },
  {
    requestId: "REQ-1003",
    blockchainId: "BC-9003",
    item: "Notebooks",
    quantity: 35,
    priority: "Medium",
    reason: "Project team documentation",
    status: "in progress",
    from: { userId: "U-103", departmentId: "D-003", departmentName: "IT" },
  },
  {
    requestId: "REQ-1004",
    blockchainId: "BC-9004",
    item: "Markers",
    quantity: 25,
    priority: "Medium",
    reason: "Whiteboard sessions",
    status: "rejected",
    from: { userId: "U-104", departmentId: "D-001", departmentName: "Finance" },
  },
  {
    requestId: "REQ-1005",
    blockchainId: "BC-9005",
    item: "Staplers",
    quantity: 15,
    priority: "Low",
    reason: "New staff joining",
    status: "approved",
    from: { userId: "U-105", departmentId: "D-004", departmentName: "Admin" },
  },
  {
    requestId: "REQ-1006",
    blockchainId: "BC-9006",
    item: "Folders",
    quantity: 60,
    priority: "High",
    reason: "Organizing reports",
    status: "pending",
    from: { userId: "U-106", departmentId: "D-002", departmentName: "HR" },
  },
  {
    requestId: "REQ-1007",
    blockchainId: "BC-9007",
    item: "Calculators",
    quantity: 20,
    priority: "Medium",
    reason: "Accounting use",
    status: "approved",
    from: {
      userId: "U-107",
      departmentId: "D-005",
      departmentName: "Accounting",
    },
  },
  {
    requestId: "REQ-1008",
    blockchainId: "BC-9008",
    item: "Printer Ink",
    quantity: 10,
    priority: "High",
    reason: "Printer refill",
    status: "waiting for supply",
    from: { userId: "U-108", departmentId: "D-003", departmentName: "IT" },
  },
  {
    requestId: "REQ-1009",
    blockchainId: "BC-9009",
    item: "Staple Pins",
    quantity: 500,
    priority: "Low",
    reason: "Daily usage",
    status: "fulfilled",
    from: { userId: "U-109", departmentId: "D-004", departmentName: "Admin" },
  },
  {
    requestId: "REQ-1010",
    blockchainId: "BC-9010",
    item: "Whiteboards",
    quantity: 5,
    priority: "Medium",
    reason: "New classrooms",
    status: "approved",
    from: {
      userId: "U-110",
      departmentId: "D-006",
      departmentName: "Education",
    },
  },
  {
    requestId: "REQ-1011",
    blockchainId: "BC-9011",
    item: "Projectors",
    quantity: 3,
    priority: "High",
    reason: "Lecture halls",
    status: "pending",
    from: {
      userId: "U-111",
      departmentId: "D-006",
      departmentName: "Education",
    },
  },
  {
    requestId: "REQ-1012",
    blockchainId: "BC-9012",
    item: "Laptop Chargers",
    quantity: 12,
    priority: "Medium",
    reason: "Replacement stock",
    status: "in progress",
    from: { userId: "U-112", departmentId: "D-003", departmentName: "IT" },
  },
];
