import { Stock } from "../reducers/StockManagementReducer";
import { FetchedRequestObj } from "../types/Request";

export const mockRequests: FetchedRequestObj[] = [
  {
    requestId: "REQ-1001",
    blockchainId: "BC-9001",
    item: "A4 Books",
    quantity: 50,
    priority: "High",
    reason: "For student examinations",
    status: "approved",
    from: { userId: "U-101", departmentId: "D-001", departmentName: "Finance" },
  },
  {
    requestId: "REQ-1002",
    blockchainId: "BC-9002",
    item: "Pens",
    quantity: 120,
    priority: "Low",
    reason: "Daily office use",
    status: "pending",
    from: { userId: "U-102", departmentId: "D-002", departmentName: "HR" },
  },
  {
    requestId: "REQ-1003",
    blockchainId: "BC-9003",
    item: "Notebooks",
    quantity: 35,
    priority: "Medium",
    reason: "Project team documentation",
    status: "in progress",
    from: { userId: "U-103", departmentId: "D-003", departmentName: "IT" },
  },
  {
    requestId: "REQ-1004",
    blockchainId: "BC-9004",
    item: "Markers",
    quantity: 25,
    priority: "Medium",
    reason: "Whiteboard sessions",
    status: "rejected",
    from: { userId: "U-104", departmentId: "D-001", departmentName: "Finance" },
  },
  {
    requestId: "REQ-1005",
    blockchainId: "BC-9005",
    item: "Staplers",
    quantity: 15,
    priority: "Low",
    reason: "New staff joining",
    status: "approved",
    from: { userId: "U-105", departmentId: "D-004", departmentName: "Admin" },
  },
  {
    requestId: "REQ-1006",
    blockchainId: "BC-9006",
    item: "Folders",
    quantity: 60,
    priority: "High",
    reason: "Organizing reports",
    status: "pending",
    from: { userId: "U-106", departmentId: "D-002", departmentName: "HR" },
  },
  {
    requestId: "REQ-1007",
    blockchainId: "BC-9007",
    item: "Calculators",
    quantity: 20,
    priority: "Medium",
    reason: "Accounting use",
    status: "approved",
    from: {
      userId: "U-107",
      departmentId: "D-005",
      departmentName: "Accounting",
    },
  },
  {
    requestId: "REQ-1008",
    blockchainId: "BC-9008",
    item: "Printer Ink",
    quantity: 10,
    priority: "High",
    reason: "Printer refill",
    status: "waiting for supply",
    from: { userId: "U-108", departmentId: "D-003", departmentName: "IT" },
  },
  {
    requestId: "REQ-1009",
    blockchainId: "BC-9009",
    item: "Staple Pins",
    quantity: 500,
    priority: "Low",
    reason: "Daily usage",
    status: "fulfilled",
    from: { userId: "U-109", departmentId: "D-004", departmentName: "Admin" },
  },
  {
    requestId: "REQ-1010",
    blockchainId: "BC-9010",
    item: "Whiteboards",
    quantity: 5,
    priority: "Medium",
    reason: "New classrooms",
    status: "approved",
    from: {
      userId: "U-110",
      departmentId: "D-006",
      departmentName: "Education",
    },
  },
  {
    requestId: "REQ-1011",
    blockchainId: "BC-9011",
    item: "Projectors",
    quantity: 3,
    priority: "High",
    reason: "Lecture halls",
    status: "pending",
    from: {
      userId: "U-111",
      departmentId: "D-006",
      departmentName: "Education",
    },
  },
  {
    requestId: "REQ-1012",
    blockchainId: "BC-9012",
    item: "Laptop Chargers",
    quantity: 12,
    priority: "Medium",
    reason: "Replacement stock",
    status: "in progress",
    from: { userId: "U-112", departmentId: "D-003", departmentName: "IT" },
  },
];

export const simpleStocks: Stock[] = [
  {
    stockId: "STK-001",
    itemName: "A4 Printing Paper",
    originalQuantity: 1200,
    currentQuantity: 950,
    costEach: 45,
    totalCost: 1200 * 45,
    dateIn: "2025-09-01",
  },
  {
    stockId: "STK-002",
    itemName: "Ballpoint Pens",
    originalQuantity: 5000,
    currentQuantity: 4200,
    costEach: 2.5,
    totalCost: 5000 * 2.5,
    dateIn: "2025-09-03",
  },
  {
    stockId: "STK-003",
    itemName: "Staplers",
    originalQuantity: 150,
    currentQuantity: 130,
    costEach: 35,
    totalCost: 150 * 35,
    dateIn: "2025-09-05",
  },
  {
    stockId: "STK-004",
    itemName: "Printer Toner Cartridge",
    originalQuantity: 45,
    currentQuantity: 38,
    costEach: 750,
    totalCost: 45 * 750,
    dateIn: "2025-09-06",
  },
  {
    stockId: "STK-005",
    itemName: "Desktop Computers",
    originalQuantity: 20,
    currentQuantity: 18,
    costEach: 9500,
    totalCost: 20 * 9500,
    dateIn: "2025-09-07",
  },
  {
    stockId: "STK-006",
    itemName: "Office Chairs",
    originalQuantity: 80,
    currentQuantity: 75,
    costEach: 1200,
    totalCost: 80 * 1200,
    dateIn: "2025-09-08",
  },
  {
    stockId: "STK-007",
    itemName: "Projectors",
    originalQuantity: 8,
    currentQuantity: 7,
    costEach: 6500,
    totalCost: 8 * 6500,
    dateIn: "2025-09-09",
  },
  {
    stockId: "STK-008",
    itemName: "Whiteboard Markers",
    originalQuantity: 300,
    currentQuantity: 250,
    costEach: 25,
    totalCost: 300 * 25,
    dateIn: "2025-09-10",
  },
  {
    stockId: "STK-009",
    itemName: "Office Desks",
    originalQuantity: 40,
    currentQuantity: 36,
    costEach: 2500,
    totalCost: 40 * 2500,
    dateIn: "2025-09-11",
  },
  {
    stockId: "STK-010",
    itemName: "Envelopes (A4)",
    originalQuantity: 2000,
    currentQuantity: 1600,
    costEach: 1.5,
    totalCost: 2000 * 1.5,
    dateIn: "2025-09-12",
  },
  {
    stockId: "STK-011",
    itemName: "External Hard Drives",
    originalQuantity: 25,
    currentQuantity: 21,
    costEach: 1800,
    totalCost: 25 * 1800,
    dateIn: "2025-09-13",
  },
  {
    stockId: "STK-012",
    itemName: "First Aid Kits",
    originalQuantity: 12,
    currentQuantity: 11,
    costEach: 350,
    totalCost: 12 * 350,
    dateIn: "2025-09-14",
  },
  {
    stockId: "STK-013",
    itemName: "Fire Extinguishers",
    originalQuantity: 6,
    currentQuantity: 6,
    costEach: 950,
    totalCost: 6 * 950,
    dateIn: "2025-09-15",
  },
  {
    stockId: "STK-014",
    itemName: "Networking Cables (Cat6)",
    originalQuantity: 500,
    currentQuantity: 420,
    costEach: 12,
    totalCost: 500 * 12,
    dateIn: "2025-09-15",
  },
  {
    stockId: "STK-015",
    itemName: "Water Dispensers",
    originalQuantity: 5,
    currentQuantity: 5,
    costEach: 2200,
    totalCost: 5 * 2200,
    dateIn: "2025-09-15",
  },
];

export type BlockchainLog = {
  transactionId: string; // unique ID for this blockchain transaction
  requestId: string; // the ID of the original request
  userId: string; // the user who initiated or approved
  department: string; // user's department
  action: string; // action taken: "created", "approved", "rejected", etc.
  status: string; // status of the request after action
  timestamp: string; // ISO string of the action
  remarks?: string; // optional details
  previousTransactionId?: string; // links to previous blockchain transaction if applicable
};

export const blockchainLogs: BlockchainLog[] = [
  {
    transactionId: "tx001",
    requestId: "req001",
    userId: "user01",
    department: "Finance",
    action: "created",
    status: "pending",
    timestamp: "2025-09-16T08:00:00Z",
  },
  {
    transactionId: "tx002",
    requestId: "req001",
    userId: "user02",
    department: "Stores",
    action: "approved",
    status: "approved",
    timestamp: "2025-09-16T09:00:00Z",
    previousTransactionId: "tx001",
  },
  {
    transactionId: "tx003",
    requestId: "req002",
    userId: "user03",
    department: "IT",
    action: "created",
    status: "pending",
    timestamp: "2025-09-16T09:30:00Z",
  },
  {
    transactionId: "tx004",
    requestId: "req002",
    userId: "user04",
    department: "Finance",
    action: "rejected",
    status: "rejected",
    timestamp: "2025-09-16T10:00:00Z",
    previousTransactionId: "tx003",
    remarks: "Budget not approved",
  },
  {
    transactionId: "tx005",
    requestId: "req003",
    userId: "user01",
    department: "Finance",
    action: "created",
    status: "pending",
    timestamp: "2025-09-16T10:30:00Z",
  },
  {
    transactionId: "tx006",
    requestId: "req003",
    userId: "user05",
    department: "CFO",
    action: "approved",
    status: "approved",
    timestamp: "2025-09-16T11:00:00Z",
    previousTransactionId: "tx005",
  },
  {
    transactionId: "tx007",
    requestId: "req004",
    userId: "user02",
    department: "Stores",
    action: "created",
    status: "pending",
    timestamp: "2025-09-16T11:30:00Z",
  },
  {
    transactionId: "tx008",
    requestId: "req004",
    userId: "user03",
    department: "Department Dean",
    action: "approved",
    status: "approved",
    timestamp: "2025-09-16T12:00:00Z",
    previousTransactionId: "tx007",
  },
  {
    transactionId: "tx009",
    requestId: "req005",
    userId: "user01",
    department: "Finance",
    action: "created",
    status: "pending",
    timestamp: "2025-09-16T12:30:00Z",
  },
  {
    transactionId: "tx010",
    requestId: "req005",
    userId: "user05",
    department: "CFO",
    action: "approved",
    status: "approved",
    timestamp: "2025-09-16T13:00:00Z",
    previousTransactionId: "tx009",
  },
  {
    transactionId: "tx011",
    requestId: "req006",
    userId: "user06",
    department: "HR",
    action: "created",
    status: "pending",
    timestamp: "2025-09-16T13:30:00Z",
  },
  {
    transactionId: "tx012",
    requestId: "req006",
    userId: "user02",
    department: "Stores",
    action: "approved",
    status: "approved",
    timestamp: "2025-09-16T14:00:00Z",
    previousTransactionId: "tx011",
  },
  {
    transactionId: "tx013",
    requestId: "req007",
    userId: "user03",
    department: "IT",
    action: "created",
    status: "pending",
    timestamp: "2025-09-16T14:30:00Z",
  },
  {
    transactionId: "tx014",
    requestId: "req007",
    userId: "user04",
    department: "Finance",
    action: "rejected",
    status: "rejected",
    timestamp: "2025-09-16T15:00:00Z",
    previousTransactionId: "tx013",
    remarks: "Insufficient funds",
  },
  {
    transactionId: "tx015",
    requestId: "req008",
    userId: "user01",
    department: "Finance",
    action: "created",
    status: "pending",
    timestamp: "2025-09-16T15:30:00Z",
  },
];
